# Meta Data for SEO

## Homepage
title = "PiRogue tool suite"
titleSeparator = "-"
titleAddition = "Mobile forensic & Network traffic analysis"
description = "PiRogue tool suite (PTS) is an open-source tool suite that provides a comprehensive mobile forensic and network traffic analysis platform targeting mobile devices both Android and iOS, internet of things devices (devices that are connected to the user mobile apps), and in general any device using wi-fi to connect to the Internet."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = []
ogLocale = "en_US"
domainTLD = "pts-project.org"
titleHome = "PiRogue tool suite"

## Twitter Cards
twitterSite = "@PiRogueTools"
twitterCreator = "@u039b"

## JSON-LD
schemaType = "Organization"
schemaName = "PiRogue tool suite"
schemaAuthor = "Esther Onfroy"
schemaAuthorTwitter = "https://twitter.com/u039b"
schemaAuthorGitHub = "https://github.com/u039b"
schemaLocale = "en-US"
schemaLogo = "android-chrome-512x512.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaTwitter = "https://twitter.com/PiRogueTools"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/PiRogueToolSuite/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 100
bgColor = "#fff"
#landscapePhotoWidths = [900, 800, 700]
#portraitPhotoWidths = [800, 700]
lqipWidth = "1800x"
smallLimit = "900"


[imaging]
  anchor = 'Smart'
  quality = 100
  resampleFilter = 'Box'


# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022-2023 Defensive Lab Agency"

# Alert
alert = true
alertDismissable = true
alertText = "If you need help or just want to chat, feel free to join <a class=\"alert-link stretched-link\" href=\"https://discord.gg/Tve3SP26QS\" target=\"_blank\" rel=\"noopener\">our Discord server</a>."


# Edit Page
# repoHost [Github | Gitea | GitLab] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/PiRogueToolSuite/"
docsRepoBranch = "main"
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
    mainSections = ["docs", "guides"]
